name: Build Android APK 🚀

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Android 🤖
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true 

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # BƯỚC MỚI: Tự động đăng nhập và xin bản quyền ngay trên máy ảo!
      - name: Tự động đăng nhập Unity
        uses: RageAgainstThePixel/activate-unity-license@v2
        with:
          license: 'Personal'
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}
          # Bạn có thể bỏ qua dòng authenticator nếu không dùng bảo mật 2 lớp

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 6000.3.10f1
          buildName: FarmPuzzle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Build-Android-APK
          path: build/Android
